//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Cfg
{
public sealed partial class ItemQualityConfig :  Bright.Config.BeanBase 
{
    public ItemQualityConfig(ByteBuf _buf) 
    {
        Quality = _buf.ReadInt();
        Ratio = _buf.ReadFloat();
        Title = _buf.ReadString();
        Icon = _buf.ReadString();
        Color = _buf.ReadString();
        PostInit();
    }

    public static ItemQualityConfig DeserializeItemQualityConfig(ByteBuf _buf)
    {
        return new Cfg.ItemQualityConfig(_buf);
    }

    /// <summary>
    /// 品质
    /// </summary>
    public int Quality { get; private set; }
    /// <summary>
    /// 系数
    /// </summary>
    public float Ratio { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Title { get; private set; }
    /// <summary>
    /// 品质icon
    /// </summary>
    public string Icon { get; private set; }
    /// <summary>
    /// 颜色
    /// </summary>
    public string Color { get; private set; }

    public const int __ID__ = 1319739780;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Quality:" + Quality + ","
        + "Ratio:" + Ratio + ","
        + "Title:" + Title + ","
        + "Icon:" + Icon + ","
        + "Color:" + Color + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}