//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Cfg
{
public sealed partial class ItemTypeConfig :  Bright.Config.BeanBase 
{
    public ItemTypeConfig(ByteBuf _buf) 
    {
        Type = _buf.ReadInt();
        Text = _buf.ReadString();
        Hp = _buf.ReadInt();
        Spd = _buf.ReadInt();
        Atk = _buf.ReadInt();
        Def = _buf.ReadInt();
        Icon = _buf.ReadString();
        PostInit();
    }

    public static ItemTypeConfig DeserializeItemTypeConfig(ByteBuf _buf)
    {
        return new Cfg.ItemTypeConfig(_buf);
    }

    /// <summary>
    /// 品种
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 中文
    /// </summary>
    public string Text { get; private set; }
    /// <summary>
    /// 血量系数
    /// </summary>
    public int Hp { get; private set; }
    /// <summary>
    /// 速度系数
    /// </summary>
    public int Spd { get; private set; }
    /// <summary>
    /// 攻击系数
    /// </summary>
    public int Atk { get; private set; }
    /// <summary>
    /// 防御系数
    /// </summary>
    public int Def { get; private set; }
    /// <summary>
    /// 品类图标
    /// </summary>
    public string Icon { get; private set; }

    public const int __ID__ = 1836896665;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Type:" + Type + ","
        + "Text:" + Text + ","
        + "Hp:" + Hp + ","
        + "Spd:" + Spd + ","
        + "Atk:" + Atk + ","
        + "Def:" + Def + ","
        + "Icon:" + Icon + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}