//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Cfg
{
   
public partial class Item
{
    private readonly Dictionary<int, Cfg.ItemConfig> _dataMap;
    private readonly List<Cfg.ItemConfig> _dataList;
    
    public Item(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Cfg.ItemConfig>();
        _dataList = new List<Cfg.ItemConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Cfg.ItemConfig _v;
            _v = Cfg.ItemConfig.DeserializeItemConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Cfg.ItemConfig> DataMap => _dataMap;
    public List<Cfg.ItemConfig> DataList => _dataList;

    public Cfg.ItemConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Cfg.ItemConfig Get(int key) => _dataMap[key];
    public Cfg.ItemConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}