//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Cfg
{
public sealed partial class PlayerLevelUpConfig :  Bright.Config.BeanBase 
{
    public PlayerLevelUpConfig(ByteBuf _buf) 
    {
        Lv = _buf.ReadInt();
        Exp = _buf.ReadInt();
        PostInit();
    }

    public static PlayerLevelUpConfig DeserializePlayerLevelUpConfig(ByteBuf _buf)
    {
        return new Cfg.PlayerLevelUpConfig(_buf);
    }

    /// <summary>
    /// 玩家等级
    /// </summary>
    public int Lv { get; private set; }
    /// <summary>
    /// 升级经验
    /// </summary>
    public int Exp { get; private set; }

    public const int __ID__ = -1598968010;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Lv:" + Lv + ","
        + "Exp:" + Exp + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}