//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Cfg
{
public sealed partial class TaskConfig :  Bright.Config.BeanBase 
{
    public TaskConfig(ByteBuf _buf) 
    {
        TaskId = _buf.ReadInt();
        NextId = _buf.ReadInt();
        Type = _buf.ReadInt();
        ConditionType = _buf.ReadInt();
        Text = _buf.ReadString();
        TargetId = _buf.ReadInt();
        TargetNum = _buf.ReadInt();
        RewardId = _buf.ReadInt();
        RewardNum = _buf.ReadInt();
        PostInit();
    }

    public static TaskConfig DeserializeTaskConfig(ByteBuf _buf)
    {
        return new Cfg.TaskConfig(_buf);
    }

    /// <summary>
    /// 任务id
    /// </summary>
    public int TaskId { get; private set; }
    /// <summary>
    /// 下一个任务id
    /// </summary>
    public int NextId { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 条件类型
    /// </summary>
    public int ConditionType { get; private set; }
    /// <summary>
    /// 任务描述
    /// </summary>
    public string Text { get; private set; }
    public int TargetId { get; private set; }
    /// <summary>
    /// 目标数量
    /// </summary>
    public int TargetNum { get; private set; }
    /// <summary>
    /// 奖励id
    /// </summary>
    public int RewardId { get; private set; }
    /// <summary>
    /// 奖励数量
    /// </summary>
    public int RewardNum { get; private set; }

    public const int __ID__ = -1814065871;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TaskId:" + TaskId + ","
        + "NextId:" + NextId + ","
        + "Type:" + Type + ","
        + "ConditionType:" + ConditionType + ","
        + "Text:" + Text + ","
        + "TargetId:" + TargetId + ","
        + "TargetNum:" + TargetNum + ","
        + "RewardId:" + RewardId + ","
        + "RewardNum:" + RewardNum + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}