//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Cfg
{
   
public partial class TbItemType
{
    private readonly Dictionary<int, Cfg.ItemTypeConfig> _dataMap;
    private readonly List<Cfg.ItemTypeConfig> _dataList;
    
    public TbItemType(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Cfg.ItemTypeConfig>();
        _dataList = new List<Cfg.ItemTypeConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Cfg.ItemTypeConfig _v;
            _v = Cfg.ItemTypeConfig.DeserializeItemTypeConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Type, _v);
        }
        PostInit();
    }

    public Dictionary<int, Cfg.ItemTypeConfig> DataMap => _dataMap;
    public List<Cfg.ItemTypeConfig> DataList => _dataList;

    public Cfg.ItemTypeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Cfg.ItemTypeConfig Get(int key) => _dataMap[key];
    public Cfg.ItemTypeConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}