//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Cfg
{
   
public partial class TreasureChest
{
    private readonly Dictionary<int, Cfg.TreasureChestConfig> _dataMap;
    private readonly List<Cfg.TreasureChestConfig> _dataList;
    
    public TreasureChest(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Cfg.TreasureChestConfig>();
        _dataList = new List<Cfg.TreasureChestConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Cfg.TreasureChestConfig _v;
            _v = Cfg.TreasureChestConfig.DeserializeTreasureChestConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.BoxLv, _v);
        }
        PostInit();
    }

    public Dictionary<int, Cfg.TreasureChestConfig> DataMap => _dataMap;
    public List<Cfg.TreasureChestConfig> DataList => _dataList;

    public Cfg.TreasureChestConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Cfg.TreasureChestConfig Get(int key) => _dataMap[key];
    public Cfg.TreasureChestConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}