//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



namespace GameConfig
{ 
public partial class Tables
{
    public Cfg.TBPlayerLevelUp TBPlayerLevelUp {get; }
    public Cfg.TbItem TbItem {get; }
    public Cfg.TbTask TbTask {get; }
    public Cfg.TbTreasureChest TbTreasureChest {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TBPlayerLevelUp = new Cfg.TBPlayerLevelUp(loader("cfg_tbplayerlevelup")); 
        tables.Add("Cfg.TBPlayerLevelUp", TBPlayerLevelUp);
        TbItem = new Cfg.TbItem(loader("cfg_tbitem")); 
        tables.Add("Cfg.TbItem", TbItem);
        TbTask = new Cfg.TbTask(loader("cfg_tbtask")); 
        tables.Add("Cfg.TbTask", TbTask);
        TbTreasureChest = new Cfg.TbTreasureChest(loader("cfg_tbtreasurechest")); 
        tables.Add("Cfg.TbTreasureChest", TbTreasureChest);

        PostInit();
        TBPlayerLevelUp.Resolve(tables); 
        TbItem.Resolve(tables); 
        TbTask.Resolve(tables); 
        TbTreasureChest.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TBPlayerLevelUp.TranslateText(translator); 
        TbItem.TranslateText(translator); 
        TbTask.TranslateText(translator); 
        TbTreasureChest.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}